version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:bionic
    steps:
      - checkout

      - run:
          name: build
          command: |
                  cmake -H. -Bbuild
                  cmake --build build
